version: '3.4'

services:
  test-type-graphql:
    image: test-type-graphql
    build: .
    environment:
      NODE_ENV: production
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_USER: "test"
      DB_PASSWORD: "test"
      DB_NAME: "test"      
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"      