version: '3.4'

services:
  test-type-graphql:
    image: test-type-graphql
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"      